### ISSUE TITLE
Mejorar filtrado manual

### ISSUE THREAD

**Issue by xam1002** [xam1002/TFG_Deteccion_Parkinson#12]
En los picos de los mínimos de las gráficas se aprecia una leve desviación. También hay que adaptar el código para poder filtrar con diferentes tipos dependiendo de un parámetro.

**Comment by alvarag** [comment]
Tal vez merece la pena probar este método que usan [Williams et al.](https://www.sciencedirect.com/science/article/pii/S0022510X20303403) en su artículo:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.savgol_filter.html

**Comment by xam1002** [comment]
Finalmente, se ha podido solucionar el problema sin programar un filtrado desde 0.
