### ISSUE TITLE
Probar mejoras en el porcentaje de acierto en modelos

### ISSUE THREAD

**Issue by xam1002** [xam1002/TFG_Deteccion_Parkinson#17]
Actualmente, se está obteniendo el resultado teniendo en cuenta la "accuracy". Hay que probar más opciones para mejorar los porcentajes de acierto.

**Comment by alvarag** [comment]
Para mejorar la descripción de la issue: Actualmente se está utilizando la _accuracy_ (porcentaje de aciertos) lo cual no es lo más acertado en un conjunto de datos desequilibrado/desbalanceado. Calcular más medidas como pueden ser la: F measure, G mean, AUC (area under ROC curve)...
