### ISSUE TITLE
Realizar la documentación técnica de programación

### ISSUE THREAD

**Issue by xam1002** [xam1002/TFG_Deteccion_Parkinson#31]

**Comment by alvarag** [comment]
Comentarios sobre memoria y anexos:

[anexosAAG.pdf](https://github.com/xam1002/TFG_Deteccion_Parkinson/files/8676443/anexosAAG.pdf)

[memoriaAAG.pdf](https://github.com/xam1002/TFG_Deteccion_Parkinson/files/8676442/memoriaAAG.pdf)
