### ISSUE TITLE
Realizar la especificación de diseño

### ISSUE THREAD

**Issue by xam1002** [xam1002/TFG_Deteccion_Parkinson#40]

**Comment by alvarag** [comment]
Algunos comentarios
[memoria_AAG.pdf](https://github.com/xam1002/TFG_Deteccion_Parkinson/files/8796390/memoria_AAG.pdf)
[anexos_AAG.pdf](https://github.com/xam1002/TFG_Deteccion_Parkinson/files/8796391/anexos_AAG.pdf)
